# Gunakan image resmi PHP dengan Apache
FROM php:8.2-apache

# Install dependencies
RUN apt-get update && apt-get install -y \
    unzip \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    postgresql-client \
    libpq-dev \ 
    && docker-php-ext-install pdo_mysql pdo_pgsql mbstring exif pcntl bcmath gd

