# Gunakan image dasar PHP 5.6 dengan Apache
FROM php:5.6-apache

# Ubah sumber repository ke archive.debian.org (karena versi ini sudah EOL)
RUN sed -i s/deb.debian.org/archive.debian.org/g /etc/apt/sources.list \
    && sed -i 's|security.debian.org|archive.debian.org|g' /etc/apt/sources.list \
    && sed -i '/stretch-updates/d' /etc/apt/sources.list

# Update sistem
RUN apt-get update

# Install Postgre PDO
RUN apt-get install -y --no-install-recommends libpq-dev \
    && docker-php-ext-configure pgsql --with-pgsql=/usr/local/pgsql \
    && docker-php-ext-install pdo pdo_pgsql pgsql \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install Redis Extension
RUN pecl install redis-4.3.0 \
    && docker-php-ext-enable redis

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Install Git
RUN apt-get update \
    && apt-get install -y git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Ganti pengguna ke www-data
USER www-data:www-data

# Direktori kerja default
WORKDIR /var/www/html

# Expose port 80 untuk Apache
EXPOSE 80

# Perintah default untuk Apache
CMD ["apache2-foreground"]
